title: Anastasia Tsvetkova
email: "tsvetkova.lea(at)gmail.com"
description: "Website of Anastasia Tsvetkova"
baseurl: ""
url: "https://anastasia-tsvetkova.github.io"
github_username: anastasia-tsvetkova

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
# footer_text: false  # отключает стандартную подпись GitHub Pages

# Site navigation
nav_pages:
  - title: "Home"
    url: "/"
  - title: "About"
    url: "/about/"
  - title: "News"
    url: "/news/"
  - title: "CV"
    url: "/cv/"
  - title: "Research"
    url: "/research/"
  - title: "Collaborations"
    url: "/collaborations/"
  - title: "Teaching"
    url: "/teaching/"
  - title: "Konus-Wind"
    url: "/kw/"
  - title: "Links"
    url: "/links/"

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
