title: Anastasia Tsvetkova
email: "tsvetkova.lea at gmail.com"
description: "Academic website of Anastasia Tsvetkova"
baseurl: ""
url: "https://anastasia-tsvetkova.github.io"
github_username: anastasia-tsvetkova

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
# footer_text: false  # отключает стандартную подпись GitHub Pages

# Site navigation
nav_pages:
  - name: "Home"
    link: "/"
  - name: "About"
    link: "/about"
  - name: "News"
    link: "/news"
  - name: "CV"
    link: "/cv"
  - name: "Research"
    link: "/research"
  - name: "Collaborations"
    link: "/collaborations"
  - name: "Teaching/Mentoring"
    link: "/teaching"
  - name: "Links"
    link: "/links"

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
